extern const int PROJECT_VERSION_MAJOR=0;
extern const int PROJECT_VERSION_MINOR=2;
extern const int PROJECT_VERSION_PATCH=0;
extern const int PROJECT_VERSION_BUILD_NUMBER=1128;
extern const int PROJECT_BUILD_NUMBER=1884;